name: Python application test  with github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        make install

    - name: Install lint
      run: |
        make lint

    - name: Test
      run: |
        make test

    - name: Format
      run: |
        make format
        
